version: "3.9"

services:
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "bash", "-c", "echo stat | nc localhost 2181"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  kafka:
    image: bitnami/kafka:3.8.0
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=false
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_CFG_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_HEAP_OPTS=-Xms512m -Xmx512m
      - ALLOW_PLAINTEXT_LISTENER=yes
    healthcheck:
      test: ["CMD", "bash", "-c", "/opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list > /dev/null"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s
    restart: unless-stopped

  schema-registry:
    image: bitnami/schema-registry:7.6.1
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      - SCHEMA_REGISTRY_KAFKA_BROKERS=PLAINTEXT://kafka:9092
      - SCHEMA_REGISTRY_HOST_NAME=schema-registry
      - SCHEMA_REGISTRY_LISTENERS=http://0.0.0.0:8081
    healthcheck:
      test: ["CMD-SHELL", "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8081'"]
      interval: 10s
      timeout: 10s
      retries: 10
    restart: unless-stopped

  kafka-setup:
    image: bitnami/kafka:3.8.0
    depends_on:
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    entrypoint: ["/bin/bash", "/scripts/create-topics.sh"]
    volumes:
      - ./scripts:/scripts:ro
    restart: "no"

  mysql:
    image: mysql:8.0
    command: >-
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_bin
      --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=datahub
      - MYSQL_USER=datahub
      - MYSQL_PASSWORD=datahub
      - MYSQL_ROOT_PASSWORD=datahub
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "datahub", "--password=datahub"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql

  mysql-setup:
    image: acryldata/datahub-mysql-setup:v1.2.0.1
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USERNAME=datahub
      - MYSQL_PASSWORD=datahub
      - DATAHUB_DB_NAME=datahub
    restart: "no"

  opensearch:
    image: opensearchproject/opensearch:2.15.0
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - DISABLE_INSTALL_DEMO_CONFIG=true
      - OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://opensearch:9200/_cluster/health?wait_for_status=yellow&timeout=1s"]
      interval: 10s
      timeout: 10s
      retries: 15
    restart: unless-stopped
    volumes:
      - opensearchdata:/usr/share/opensearch/data

  opensearch-setup:
    image: acryldata/datahub-elasticsearch-setup:v1.2.0.1
    depends_on:
      opensearch:
        condition: service_healthy
    environment:
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - ELASTICSEARCH_USE_SSL=false
      - USE_AWS_ELASTICSEARCH=false
      - DATAHUB_ANALYTICS_ENABLED=false
    restart: "no"

  datahub-upgrade:
    image: acryldata/datahub-upgrade:v1.2.0.1
    depends_on:
      mysql-setup:
        condition: service_completed_successfully
      opensearch-setup:
        condition: service_completed_successfully
      kafka-setup:
        condition: service_completed_successfully
    environment:
      - BACKFILL_BROWSE_PATHS_V2=true
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8
      - EBEAN_DATASOURCE_USERNAME=datahub
      - ELASTICSEARCH_BUILD_INDICES_CLONE_INDICES=false
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
      - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
      - ELASTICSEARCH_PORT=9200
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
      - GRAPH_SERVICE_IMPL=elasticsearch
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - REPROCESS_DEFAULT_BROWSE_PATHS_V2=false
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
    command: ["-u", "SystemUpdate"]
    restart: "no"

  datahub-gms:
    image: acryldata/datahub-gms:v1.2.0.1
    depends_on:
      mysql:
        condition: service_healthy
      opensearch:
        condition: service_healthy
      kafka:
        condition: service_healthy
      schema-registry:
        condition: service_healthy
    environment:
      - DATAHUB_SERVER_TYPE=quickstart
      - DATAHUB_TELEMETRY_ENABLED=true
      - DATAHUB_UPGRADE_HISTORY_KAFKA_CONSUMER_GROUP_ID=generic-duhe-consumer-job-client-gms
      - EBEAN_DATASOURCE_DRIVER=com.mysql.jdbc.Driver
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?verifyServerCertificate=false&useSSL=true&useUnicode=yes&characterEncoding=UTF-8&enabledTLSProtocols=TLSv1.2
      - EBEAN_DATASOURCE_USERNAME=datahub
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - ELASTICSEARCH_INDEX_BUILDER_MAPPINGS_REINDEX=true
      - ELASTICSEARCH_INDEX_BUILDER_SETTINGS_REINDEX=true
      - ELASTICSEARCH_LIMIT_RESULTS_STRICT=true
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-gms/resources/entity-registry.yml
      - ENTITY_SERVICE_ENABLE_RETENTION=true
      - ES_BULK_REFRESH_POLICY=WAIT_UNTIL
      - GRAPH_SERVICE_DIFF_MODE_ENABLED=true
      - GRAPH_SERVICE_IMPL=elasticsearch
      - JAVA_OPTS=-Xms1g -Xmx1g
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_CONSUMER_STOP_ON_DESERIALIZATION_ERROR=true
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - MAE_CONSUMER_ENABLED=true
      - MCE_CONSUMER_ENABLED=true
      - METADATA_SERVICE_AUTH_ENABLED=false
      - NEO4J_HOST=http://neo4j:7474
      - NEO4J_PASSWORD=datahub
      - NEO4J_URI=bolt://neo4j
      - NEO4J_USERNAME=neo4j
      - PE_CONSUMER_ENABLED=true
      - DATAHUB_ANALYTICS_ENABLED=false
      - THEME_V2_DEFAULT=true
      - UI_INGESTION_ENABLED=true
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 30
      start_period: 120s
    restart: unless-stopped

  datahub-mce-consumer:
    image: acryldata/datahub-mce-consumer:v1.2.0.1
    depends_on:
      datahub-gms:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - GRAPH_SERVICE_IMPL=elasticsearch
      - SKIP_NEO4J_CHECK=true
      - NEO4J_HOST=http://neo4j:7474
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-mce-consumer/resources/entity-registry.yml
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?characterEncoding=UTF-8&useSSL=false
      - EBEAN_DATASOURCE_USERNAME=datahub
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - METADATA_AUDIT_EVENT_CONSUMER_ENABLED=true
      - METADATA_CHANGE_EVENT_CONSUMER_ENABLED=true
      - DATAHUB_CONSUMER_ID=datahub-mce-consumer
    restart: unless-stopped

  datahub-mae-consumer:
    image: acryldata/datahub-mae-consumer:v1.2.0.1
    depends_on:
      datahub-gms:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - KAFKA_SCHEMAREGISTRY_URL=http://schema-registry:8081
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - ELASTICSEARCH_HOST=opensearch
      - ELASTICSEARCH_PORT=9200
      - ELASTICSEARCH_PROTOCOL=http
      - GRAPH_SERVICE_IMPL=elasticsearch
      - SKIP_NEO4J_CHECK=true
      - NEO4J_HOST=http://neo4j:7474
      - ENTITY_REGISTRY_CONFIG_PATH=/datahub/datahub-mae-consumer/resources/entity-registry.yml
      - EBEAN_DATASOURCE_URL=jdbc:mysql://mysql:3306/datahub?characterEncoding=UTF-8&useSSL=false
      - EBEAN_DATASOURCE_USERNAME=datahub
      - EBEAN_DATASOURCE_PASSWORD=datahub
      - EBEAN_DATASOURCE_HOST=mysql:3306
      - DATAHUB_CONSUMER_ID=datahub-mae-consumer
      - UI_INGESTION_ENABLED=true
    restart: unless-stopped

  datahub-frontend:
    image: acryldata/datahub-frontend-react:v1.2.0.1
    depends_on:
      datahub-gms:
        condition: service_healthy
    environment:
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - DATAHUB_SECRET=YouKnowNothing
      - DATAHUB_APP_VERSION=1.0
      - DATAHUB_PLAY_MEM_BUFFER_SIZE=10MB
      - JAVA_OPTS=-Xms512m -Xmx512m -Dhttp.port=9002 -Dconfig.file=datahub-frontend/conf/application.conf -Djava.security.auth.login.config=datahub-frontend/conf/jaas.conf -Dlogback.configurationFile=datahub-frontend/conf/logback.xml -Dlogback.debug=false -Dpidfile.path=/dev/null
      - KAFKA_BOOTSTRAP_SERVER=kafka:9092
      - DATAHUB_TRACKING_TOPIC=DataHubUsageEvent_v1
      - ELASTIC_CLIENT_HOST=opensearch
      - ELASTIC_CLIENT_PORT=9200
    ports:
      - "9002:9002"
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://datahub-frontend:9002"]
      interval: 10s
      timeout: 10s
      retries: 20
    restart: unless-stopped

  ingestion:
    image: acryldata/datahub-ingestion:v1.2.0.1
    depends_on:
      datahub-gms:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATAHUB_GMS_URL=http://datahub-gms:8080
      - DATAHUB_GMS_PROTOCOL=http
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
    volumes:
      - ./ingest:/ingest:ro
    working_dir: /ingest
    command: ["sleep", "infinity"]

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=datahub
      - POSTGRES_PASSWORD=datahub
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init/sql:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "datahub"]
      interval: 5s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  base64-action:
    image: python:3.11-slim
    depends_on:
      datahub-gms:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATAHUB_GMS_URL=http://datahub-gms:8080
      - DATAHUB_GMS_PROTOCOL=http
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - DATAHUB_RUN_POLL_INTERVAL=15
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
      - POSTGRES_USER=datahub
      - POSTGRES_PASSWORD=datahub
    volumes:
      - ./actions/base64_action:/app
    working_dir: /app
    command: /bin/bash -lc "set -euo pipefail; python -m pip install --no-cache-dir -r requirements.txt; python -u action.py"
    restart: unless-stopped

  ui-ingestion-runner:
    image: acryldata/datahub-ingestion:v1.2.0.1
    depends_on:
      datahub-gms:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      - DATAHUB_GMS_URL=http://datahub-gms:8080
      - DATAHUB_GMS_PROTOCOL=http
      - DATAHUB_GMS_HOST=datahub-gms
      - DATAHUB_GMS_PORT=8080
      - UI_RUNNER_POLL_INTERVAL=15
    volumes:
      - ./scripts:/scripts:ro
      - ./actions:/actions:ro
    working_dir: /scripts
    entrypoint: ["python", "-u", "ui_ingestion_runner.py"]
    restart: unless-stopped

volumes:
  mysqldata:
  opensearchdata:
  pgdata:
