source:
  type: postgres
  config:
    host: ${PG_HOST:-localhost}
    port: ${PG_PORT:-5432}
    database: ${PG_DB:-sandbox}
    username: ${PG_USER}
    password: ${PG_PASSWORD}
    include_tables: true
    include_views: true
    profiling:
      enabled: false
    schema_pattern:
      allow:
        - ${PG_SCHEMA_PATTERN:-t001}

sink:
  type: datahub-rest
  config:
    server: ${DATAHUB_GMS:-http://localhost:8080}
