gms_url: http://localhost:8080
platform: postgres
pipeline_name: postgres_local_poc
poll_interval_seconds: 15
page_size: 100
database:
  host: localhost
  port: 5432
  dbname: lseat
  user: postgres
  password: datahub
