apiVersion: v1
kind: Service
metadata:
  name: prerequisites-mysql
  namespace: datahub
  labels:
    app: prerequisites-mysql
spec:
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  selector:
    app: prerequisites-mysql
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prerequisites-mysql
  namespace: datahub
spec:
  serviceName: prerequisites-mysql
  replicas: 1
  selector:
    matchLabels:
      app: prerequisites-mysql
  template:
    metadata:
      labels:
        app: prerequisites-mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_bin"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              value: datahub
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
